<?php
/**
 * Created by PhpStorm.
 * User: zhu
 * Date: 2017/4/12
 * Time: 下午3:28
 */

namespace App\Repositories\Eloquent;


use App\Exceptions\DataNullException;
use Bosnadev\Repositories\Eloquent\Repository;

abstract class BaseRepository extends Repository
{
    public function find($hid, $columns = array('*'))
    {
        $result = parent::findWhere(['hid' => $hid])->first();
         if (empty($result) ){
             throw new DataNullException();
         } else {
             return $result;
         }
    }

    public function delete($hid)
    {
        $this->find($hid);
        return $this->model->where('hid',$hid)->delete();
    }

    public function update(array $data, $hid, $attribute = "hid")
    {
        return parent::update($data, $hid, $attribute); // TODO: Change the autogenerated stub
    }

}